export default {
        
    LOGIN_STARTED: "LOGIN_STARTED",

    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    LOGIN_FAILED: "LOGIN_FAILED",

    SIGNUP_STARTED: "SIGNUP_STARTED",

    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

    SIGNUP_FAILED: "SIGNUP_FAILED",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",

    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    
    LOGOUT_FAILED: "LOGOUT_FAILED",

    VERIFY_FAILED: "VERIFY_FAILED",

    CHANGE_PASSWORD_STARTED: "CHANGE_PASSWORD_STARTED",

    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",

    CHANGE_PASSWORD_FAILED: "CHANGE_PASSWORD_FAILED",
    
    CLEAR_ERROR_MESSAGE: "CLEAR_ERROR_MESSAGE",

};