export default {
        
    FETCH_FARES_START: "FETCH_FARES_START",
    FETCH_FARES_SUCCESS: "FETCH_FARES_SUCCESS",
    FETCH_FARES_FAILURE: "FETCH_FARES_FAILURE",

    CREATE_FARE_START: "CREATE_FARE_START",
    CREATE_FARE_SUCCESS: "CREATE_FARE_SUCCESS",
    CREATE_FARE_FAILURE: "CREATE_FARE_FAILURE",

    DELETE_FARE_START: "DELETE_FARE_START",
    DELETE_FARE_SUCCESS: "DELETE_FARE_SUCCESS",
    DELETE_FARE_FAILURE: "DELETE_FARE_FAILURE",

    UPDATE_FARE_START: "UPDATE_FARE_START",
    UPDATE_FARE_SUCCESS: "UPDATE_FARE_SUCCESS",
    UPDATE_FARE_FAILURE: "UPDATE_FARE_FAILURE",

    FETCH_PROFILE_START: "FETCH_PROFILE_START",
    FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
    FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",
    
    UPDATE_COMPANY_DETAILS_START: "UPDATE_COMPANY_DETAILS_START",
    UPDATE_COMPANY_DETAILS_SUCCESS: "UPDATE_COMPANY_DETAILS_SUCCESS",
    UPDATE_COMPANY_DETAILS_FAILURE: "UPDATE_COMPANY_DETAILS_FAILURE",

    UPDATE_MANAGER_DETAILS_START: "UPDATE_MANAGER_DETAILS_START",
    UPDATE_MANAGER_DETAILS_SUCCESS: "UPDATE_MANAGER_DETAILS_SUCCESS",
    UPDATE_MANAGER_DETAILS_FAILURE: "UPDATE_MANAGER_DETAILS_FAILURE",

    UPDATE_OWNER_DETAILS_START: "UPDATE_OWNER_DETAILS_START",
    UPDATE_OWNER_DETAILS_SUCCESS: "UPDATE_OWNER_DETAILS_SUCCESS",
    UPDATE_OWNER_DETAILS_FAILURE: "UPDATE_OWNER_DETAILS_FAILURE",

};